## NUMPY

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [3]:
## Creating an array

In [6]:
x=np.array([[1,2,3],[2,3,4],[4,5,6]])
x

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [7]:
np.shape(x)

(3, 3)

In [8]:
np.size(x)

9

In [11]:
np.ndim(x)

2

In [12]:
x.itemsize

4

In [13]:
x.dtype

dtype('int32')

In [14]:
### Reshape

In [15]:
y=np.array([[1,2,3],[3,4,5]])

In [16]:
y

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
y.reshape(3,2)

array([[1, 2],
       [3, 3],
       [4, 5]])

In [18]:
y.reshape(1,6)

array([[1, 2, 3, 3, 4, 5]])

In [19]:
y.reshape(6,1)

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [20]:
### Slicing

In [21]:
x

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [22]:
x[0,1]

2

In [23]:
x[:,1:2]

array([[2],
       [3],
       [5]])

In [24]:
x[1]

array([2, 3, 4])

In [30]:
x[:,0]

array([1, 2, 4])

In [31]:
x[:,-1]

array([3, 4, 6])

In [32]:
x[:,2]

array([3, 4, 6])

In [37]:
x[:,0::2]

array([[1, 3],
       [2, 4],
       [4, 6]])

In [38]:
x[:,0:2]

array([[1, 2],
       [2, 3],
       [4, 5]])

In [44]:
a=np.array([[1,2,3],[4,5,6],[9,0,7]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [9, 0, 7]])

In [47]:
a[2,2]

7

In [48]:
## Accessing rows 
a[0:,1]

array([2, 5, 0])

In [51]:
a[:,0::2]

array([[1, 3],
       [4, 6],
       [9, 7]])

In [53]:
a[:,1::]

array([[2, 3],
       [5, 6],
       [0, 7]])

In [54]:
a[1:,0::2]

array([[4, 6],
       [9, 7]])

In [57]:
a[2:,0::2]

array([[9, 7]])

In [60]:
k=np.linspace(0,4,10)
k

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [61]:
## maximum and minimum values

In [62]:
a.max()

4.0

In [66]:
x

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [67]:
x.min()

1

In [68]:
x.sum()

30

In [69]:
x.mean()

3.3333333333333335

In [70]:
x.min(axis=1)

array([1, 2, 4])

In [71]:
x.max(axis=1)

array([3, 4, 6])

In [72]:
x.min(axis=0)

array([1, 2, 3])

In [73]:
x.max(axis=0)

array([4, 5, 6])

In [74]:
x

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [75]:
x.sum(axis=1)

array([ 6,  9, 15])

In [76]:
## Sqareroot

In [77]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ],
       [2.        , 2.23606798, 2.44948974]])

In [78]:
np.std(x)

1.4907119849998598

## Horizontal and vertical stacking

In [81]:
l=np.array([[1,2,3],[5,6,7],[4,3,2]])
k=np.array([[9,8,7],[6,5,4],[8,6,5]])
np.vstack((l,k))

array([[1, 2, 3],
       [5, 6, 7],
       [4, 3, 2],
       [9, 8, 7],
       [6, 5, 4],
       [8, 6, 5]])

In [83]:
np.hstack((l,k))

array([[1, 2, 3, 9, 8, 7],
       [5, 6, 7, 6, 5, 4],
       [4, 3, 2, 8, 6, 5]])

In [85]:
np.ravel((l,k))  ## Gives output in single row

array([1, 2, 3, 5, 6, 7, 4, 3, 2, 9, 8, 7, 6, 5, 4, 8, 6, 5])

In [86]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
for i in np.arange(1,7):
    print(l)

[[1 2 3]
 [5 6 7]
 [4 3 2]]
[[1 2 3]
 [5 6 7]
 [4 3 2]]
[[1 2 3]
 [5 6 7]
 [4 3 2]]
[[1 2 3]
 [5 6 7]
 [4 3 2]]
[[1 2 3]
 [5 6 7]
 [4 3 2]]
[[1 2 3]
 [5 6 7]
 [4 3 2]]


In [91]:
np.sin(l)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ],
       [-0.7568025 ,  0.14112001,  0.90929743]])

In [93]:
np.sin(l)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ],
       [-0.7568025 ,  0.14112001,  0.90929743]])

In [94]:
np.cos(l)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [ 0.28366219,  0.96017029,  0.75390225],
       [-0.65364362, -0.9899925 , -0.41614684]])

In [95]:
np.tan(l)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [-3.38051501, -0.29100619,  0.87144798],
       [ 1.15782128, -0.14254654, -2.18503986]])

### PANDAS

In [97]:
import pandas as pd

In [98]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [99]:
### Creating a series data type


In [100]:
q=pd.Series([1,2,3,4,5])
q

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [104]:
k=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
k

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [108]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key 

## DATA FRAMES

In [148]:
a=(1,2,3,4)
b=(4,5,6,7)
df=pd.DataFrame({'m':a,'n':b})
df

m  n
0  1  4
1  2  5
2  3  6
3  4  7

In [146]:
## slincing
## changing index 
## changing column headers
## merging
## operation
## concatination
## monging

In [121]:
d_f=pd.DataFrame({'x':[2,3,4,5],'y':[3,5,7,0]},index=['a','b','c','d'],dtype=float)
d_f

x    y
a  2.0  3.0
b  3.0  5.0
c  4.0  7.0
d  5.0  0.0

In [126]:
d=[[1,2,3,4],[3,555,66,77]]

In [131]:
d_f=pd.DataFrame(d,columns=["s","u","p","r"],index=["m","s"])

In [132]:
d_f

s    u   p   r
m  1    2   3   4
s  3  555  66  77

In [133]:
d_f.shape

(2, 4)

In [134]:
d_f.ndim

2

In [135]:
d_f.size

8

In [137]:
d_f.isnull()

s      u      p      r
m  False  False  False  False
s  False  False  False  False

In [141]:
d_f.head(1)

s  u  p  r
m  1  2  3  4

In [142]:
d_f.tail(2)

s    u   p   r
m  1    2   3   4
s  3  555  66  77

In [143]:
d_f.tail()

s    u   p   r
m  1    2   3   4
s  3  555  66  77

## Merging and joining

In [149]:
d_f

s    u   p   r
m  1    2   3   4
s  3  555  66  77

In [160]:
d2=[[1,2,3,4],[5,6,7,8]]
df2=pd.DataFrame(d2,columns=['s','u','p','r'],index=["mani","suu"])
df2

s  u  p  r
mani  1  2  3  4
suu   5  6  7  8

In [166]:
m=pd.merge(d_f,df2)### merge :columns must be same
m

s  u  p  r
0  1  2  3  4

In [165]:
k=df2.join(df)  ### columns must be different in join
k

s  u  p  r   m   n
mani  1  2  3  4 NaN NaN
suu   5  6  7  8 NaN NaN

In [184]:
m1=[[1,2,34,4],[3,4,5,6],[6,7,8,9],[3,4,7,8]]
f1=pd.DataFrame(m1,columns=["a","b","c","d"],index=[1,2,3,4])
f1

a  b   c  d
1  1  2  34  4
2  3  4   5  6
3  6  7   8  9
4  3  4   7  8

In [190]:
m2=[[1,2,34,4],[3,4,5,6],[3,4,6,7],[3,4,6,8]]
f2=pd.DataFrame(m2,columns=['a','b','c','d'],index=[11,22,33,44])
f2

a  b   c  d
11  1  2  34  4
22  3  4   5  6
33  3  4   6  7
44  3  4   6  8

In [191]:
k=pd.merge(f1,f2)
k

a  b   c  d
0  1  2  34  4
1  3  4   5  6

In [181]:
x=[[1,2,3,5],[4,5,8,6]]
f3=pd.DataFrame(x,columns=['aa','ss','dd','ff'],index=['xx','yy'])
f3

aa  ss  dd  ff
xx   1   2   3   5
yy   4   5   8   6

In [195]:
f4=pd.DataFrame({'name':[45,6,7],'gender':[1,0,7]})
f4

name  gender
0    45       1
1     6       0
2     7       7

In [196]:
join=f3.join(f4)

In [197]:
join

aa  ss  dd  ff  name  gender
xx   1   2   3   5   NaN     NaN
yy   4   5   8   6   NaN     NaN

## Concat

In [198]:
c=pd.concat([f3,f4])
c

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


aa   dd   ff  gender  name   ss
xx  1.0  3.0  5.0     NaN   NaN  2.0
yy  4.0  8.0  6.0     NaN   NaN  5.0
0   NaN  NaN  NaN     1.0  45.0  NaN
1   NaN  NaN  NaN     0.0   6.0  NaN
2   NaN  NaN  NaN     7.0   7.0  NaN

In [199]:
c.isnull()

aa     dd     ff  gender   name     ss
xx  False  False  False    True   True  False
yy  False  False  False    True   True  False
0    True   True   True   False  False   True
1    True   True   True   False  False   True
2    True   True   True   False  False   True

In [200]:
c.notnull()

aa     dd     ff  gender   name     ss
xx   True   True   True   False  False   True
yy   True   True   True   False  False   True
0   False  False  False    True   True  False
1   False  False  False    True   True  False
2   False  False  False    True   True  False

In [201]:
c.columns

Index(['aa', 'dd', 'ff', 'gender', 'name', 'ss'], dtype='object')

In [202]:
c

aa   dd   ff  gender  name   ss
xx  1.0  3.0  5.0     NaN   NaN  2.0
yy  4.0  8.0  6.0     NaN   NaN  5.0
0   NaN  NaN  NaN     1.0  45.0  NaN
1   NaN  NaN  NaN     0.0   6.0  NaN
2   NaN  NaN  NaN     7.0   7.0  NaN

In [210]:
### Changing index
f=pd.DataFrame({1:[1,2,3],2:[3,4,5],'i':['x','y','r']})
f.set_index('i')

1  2
i      
x  1  3
y  2  4
r  3  5

In [213]:
### Changing columns headres
c2=f.rename(columns={1:'a',2:'b'})

In [215]:
c2

a  b  i
0  1  3  x
1  2  4  y
2  3  5  r

In [217]:
## Data munging
m=pd.read_csv("mani.csv")
m

a   d   f
0  2  88   2
1  3  77   3
2  4  66   4
3  5  55   5
4  6  44  54