In [1]:
## Element accessing rows/columns
## loc and iloc --------->location and index location based

In [12]:
import pandas as pd
d=pd.DataFrame({"name":['chinni','nani','push','pop'],"rollno":[471,472,453,567],"branch":['ece','cse','civil','eee']})

In [13]:
d

name  rollno branch
0  chinni     471    ece
1    nani     472    cse
2    push     453  civil
3     pop     567    eee

In [14]:
d=pd.DataFrame({"name":['chinni','nani','push','pop'],"rollno":[471,472,453,567],"branch":['ece','cse','civil','eee']},index=[1,2,3,4])

In [15]:
d

name  rollno branch
1  chinni     471    ece
2    nani     472    cse
3    push     453  civil
4     pop     567    eee

In [19]:
d.loc[1]

name      chinni
rollno       471
branch       ece
Name: 1, dtype: object

In [20]:
d.loc[2]

name      nani
rollno     472
branch     cse
Name: 2, dtype: object

In [21]:
d.loc[2]['rollno']

472

In [23]:
d.iloc[0] ### will always takes index from zero ###

name      chinni
rollno       471
branch       ece
Name: 1, dtype: object

In [25]:
d.iloc[3]

name      pop
rollno    567
branch    eee
Name: 4, dtype: object

In [26]:
d.iloc[2]['branch']

'civil'

In [28]:
d.iloc[1]['name']

'nani'

In [29]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 3 columns):
name      4 non-null object
rollno    4 non-null int64
branch    4 non-null object
dtypes: int64(1), object(2)
memory usage: 288.0+ bytes


In [30]:
d.describe()   #### it only gives result to only integers

rollno
count    4.000000
mean   490.750000
std     51.577611
min    453.000000
25%    466.500000
50%    471.500000
75%    495.750000
max    567.000000

In [32]:
d.count()

name      4
rollno    4
branch    4
dtype: int64

In [33]:
d.dtypes

name      object
rollno     int64
branch    object
dtype: object

In [36]:
d.count(axis=0)

name      4
rollno    4
branch    4
dtype: int64

In [37]:
d.count(axis=1)

1    3
2    3
3    3
4    3
dtype: int64

In [38]:
d.count(axis='rows')

name      4
rollno    4
branch    4
dtype: int64

In [39]:
d.count('columns')

1    3
2    3
3    3
4    3
dtype: int64

In [40]:
d

name  rollno branch
1  chinni     471    ece
2    nani     472    cse
3    push     453  civil
4     pop     567    eee

In [41]:
d.set_index(["rollno"])

name branch
rollno               
471     chinni    ece
472       nani    cse
453       push  civil
567        pop    eee

In [42]:
d.set_index(['rollno','name'])

branch
rollno name         
471    chinni    ece
472    nani      cse
453    push    civil
567    pop       eee

In [57]:
import numpy as np
fr=pd.Series([1,2,5,44,99,88],[1,3,0,7,6,8])
fr

1     1
3     2
0     5
7    44
6    99
8    88
dtype: int64

In [58]:
fr.isnull()

1    False
3    False
0    False
7    False
6    False
8    False
dtype: bool

In [59]:
fr.describe()

count     6.000000
mean     39.833333
std      44.700858
min       1.000000
25%       2.750000
50%      24.500000
75%      77.000000
max      99.000000
dtype: float64

In [60]:
fr.count()

6

In [61]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [62]:
x=np.arange(2,10)
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x.reshape(2,4)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [67]:
data=pd.DataFrame(np.arange(12))
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [68]:
data=pd.DataFrame(np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [71]:
data2=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))

In [72]:
data2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [77]:
data2.loc[1,'b']=np.nan
data2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [78]:
data2.isnull()

a      b      c      d      e
0  False  False  False  False  False
1  False   True  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False

In [79]:
data2.isnull().sum()

a    0
b    1
c    0
d    0
e    0
dtype: int64

In [80]:
data+data2

0   1   2   a   b   c   d   e
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

In [87]:
df=d.add(data2)
df

a   b branch   c   d   e name  rollno
0 NaN NaN    NaN NaN NaN NaN  NaN     NaN
1 NaN NaN    NaN NaN NaN NaN  NaN     NaN
2 NaN NaN    NaN NaN NaN NaN  NaN     NaN
3 NaN NaN    NaN NaN NaN NaN  NaN     NaN
4 NaN NaN    NaN NaN NaN NaN  NaN     NaN

In [90]:
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [92]:
data2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [101]:
df.add(data2,fill_value=4)


a     b branch     c     d     e name  rollno
0   4.0   5.0    NaN   6.0   7.0   8.0  NaN     NaN
1   9.0   NaN    NaN  11.0  12.0  13.0  NaN     NaN
2  14.0  15.0    NaN  16.0  17.0  18.0  NaN     NaN
3  19.0  20.0    NaN  21.0  22.0  23.0  NaN     NaN
4   NaN   NaN    NaN   NaN   NaN   NaN  NaN     NaN

In [106]:
np.random.rand(2,4)

array([[0.85019473, 0.03794732, 0.35276492, 0.81698959],
       [0.26775809, 0.49626923, 0.70013157, 0.49706538]])

In [108]:
np.random.randn(3,3)

array([[ 0.08102992, -1.07721243,  0.5171761 ],
       [-2.07540002, -1.04040419,  0.61047329],
       [ 0.86161175, -0.36164592,  0.74124244]])

### Creating a Data frame with random values

In [129]:
p=pd.DataFrame(np.random.randn(3,4))
p

0         1         2         3
0 -1.976275 -0.225958 -0.169131 -0.396236
1 -0.070384 -0.827858  0.012341 -0.403846
2  0.045393 -0.507102 -0.952889  1.115457

In [130]:
#p=pd.DataFrame(np.random.randn(3,4),index=['a','b','c'],columns=['s1','s2','s3','s4'])
#p

In [131]:
p.index=['a','b','c']  ## adding index
p

0         1         2         3
a -1.976275 -0.225958 -0.169131 -0.396236
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457

In [136]:
p.columns=['s1','s2','s4','s3'] ##adding columns

In [137]:
p

s1        s2        s4        s3
a -1.976275 -0.225958 -0.169131 -0.396236
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457

### Re-indexing

In [138]:
p1=p.reindex(['b','c','d','a'])
p1

s1        s2        s4        s3
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d       NaN       NaN       NaN       NaN
a -1.976275 -0.225958 -0.169131 -0.396236

In [147]:
p1.isnull().sum()

s1    1
s2    1
s4    1
s3    1
dtype: int64

In [148]:
p1.dropna()

s1        s2        s4        s3
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
a -1.976275 -0.225958 -0.169131 -0.396236

In [149]:
p1.fillna(1)  ### Fill null valus with given number

s1        s2        s4        s3
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d  1.000000  1.000000  1.000000  1.000000
a -1.976275 -0.225958 -0.169131 -0.396236

In [150]:
p1.fillna(method='bfill',axis=0).fillna(1)  ### bfill--->backward fill

s1        s2        s4        s3
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d -1.976275 -0.225958 -0.169131 -0.396236
a -1.976275 -0.225958 -0.169131 -0.396236

In [151]:
p1.fillna(method='ffill',axis=0).fillna(1)

s1        s2        s4        s3
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d  0.045393 -0.507102 -0.952889  1.115457
a -1.976275 -0.225958 -0.169131 -0.396236

In [152]:
p1.isna()

s1     s2     s4     s3
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True
a  False  False  False  False

In [153]:
p1.isnull()

s1     s2     s4     s3
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True
a  False  False  False  False

In [158]:
pd.isna(p1['s4'])

b    False
c    False
d     True
a    False
Name: s4, dtype: bool

In [160]:
pd.isna(p1['s2'])

b    False
c    False
d     True
a    False
Name: s2, dtype: bool

#### Replacing

In [162]:
p1

s1        s2        s4        s3
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d       NaN       NaN       NaN       NaN
a -1.976275 -0.225958 -0.169131 -0.396236

In [165]:
p1.replace(['b','c','d','a'],6)

s1        s2        s4        s3
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d       NaN       NaN       NaN       NaN
a -1.976275 -0.225958 -0.169131 -0.396236

In [205]:
m=pd.DataFrame({11:[5,6,7],12:[2,3,6],13:[3,5,6]})

In [210]:
m.replace(6,5555)

11    12    13
0     5     2     3
1  5555     3     5
2     7  5555  5555

In [212]:
m.replace([3,7,5],555)

11   12   13
0  555    2  555
1    6  555  555
2  555    6    6

In [216]:
m.replace([5,6,7],[2,3,4])

11  12  13
0   2   2   3
1   3   3   2
2   4   3   3

In [217]:
m.replace({6:40,5:55})

11  12  13
0  55   2   3
1  40   3  55
2   7  40  40

In [218]:
p1


s4        s1        s3        s2
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d       NaN       NaN       NaN       NaN
a -1.976275 -0.225958 -0.169131 -0.396236

In [171]:
## Indexing sorting and ranking
p2=p1.reindex(['x','z','y','w'])
p2

s1  s2  s4  s3
x NaN NaN NaN NaN
z NaN NaN NaN NaN
y NaN NaN NaN NaN
w NaN NaN NaN NaN

In [173]:
p2.sort_index()

s1  s2  s4  s3
w NaN NaN NaN NaN
x NaN NaN NaN NaN
y NaN NaN NaN NaN
z NaN NaN NaN NaN

In [177]:
p1.columns=['s4','s1','s3','s2']

In [178]:
p1

s4        s1        s3        s2
b -0.070384 -0.827858  0.012341 -0.403846
c  0.045393 -0.507102 -0.952889  1.115457
d       NaN       NaN       NaN       NaN
a -1.976275 -0.225958 -0.169131 -0.396236

In [179]:
p1.sort_index(axis=1)## to make coluns in ascending order

s1        s2        s3        s4
b -0.827858 -0.403846  0.012341 -0.070384
c -0.507102  1.115457 -0.952889  0.045393
d       NaN       NaN       NaN       NaN
a -0.225958 -0.396236 -0.169131 -1.976275

### Groupby

In [181]:
animal=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],
                     'place':['zoo','home','ooo','home','zoo'],
                     'feature':['s','l','k','k','l']})

In [182]:
animal

name place feature
0  dog   zoo       s
1  cat  home       l
2  cow   ooo       k
3  dog  home       k
4  cat   zoo       l

In [183]:
animal.groupby('name')

In [184]:
animal.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [185]:
animal.groupby('name').sum()

place feature
name                 
cat   homezoo      ll
cow       ooo       k
dog   zoohome      sk

In [187]:
animal.groupby(['name','place']).sum()

feature
name place        
cat  home        l
     zoo         l
cow  ooo         k
dog  home        k
     zoo         s

In [188]:
animal.groupby(['feature']).sum()

name    place
feature                 
k        cowdog  ooohome
l        catcat  homezoo
s           dog      zoo

In [191]:
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],
                     'place':['zoo','home','ooo','home','zoo'],
                     'no-legs':[4,2,3,4,np.nan]})

In [192]:
animal_df

name place  no-legs
0  dog   zoo      4.0
1  cat  home      2.0
2  cow   ooo      3.0
3  dog  home      4.0
4  cat   zoo      NaN

In [193]:
animal_df['rank1']=animal_df['no-legs'].rank()

In [194]:
animal_df

name place  no-legs  rank1
0  dog   zoo      4.0    3.5
1  cat  home      2.0    1.0
2  cow   ooo      3.0    2.0
3  dog  home      4.0    3.5
4  cat   zoo      NaN    NaN

In [195]:
animal_df['max-rank1']=animal_df['no-legs'].rank(method="max")

In [196]:
animal_df

name place  no-legs  rank1  max-rank1
0  dog   zoo      4.0    3.5        4.0
1  cat  home      2.0    1.0        1.0
2  cow   ooo      3.0    2.0        2.0
3  dog  home      4.0    3.5        4.0
4  cat   zoo      NaN    NaN        NaN

In [197]:
animal_df['first-rank1']=animal_df['no-legs'].rank(method="first")

In [198]:
animal_df

name place  no-legs  rank1  max-rank1  first-rank1
0  dog   zoo      4.0    3.5        4.0          3.0
1  cat  home      2.0    1.0        1.0          1.0
2  cow   ooo      3.0    2.0        2.0          2.0
3  dog  home      4.0    3.5        4.0          4.0
4  cat   zoo      NaN    NaN        NaN          NaN

In [200]:
animal_df["non-rank"]=animal_df['no-legs'].rank(na_option="bottom")

In [201]:
animal_df

name place  no-legs  rank1  max-rank1  first-rank1  non-rank
0  dog   zoo      4.0    3.5        4.0          3.0       3.5
1  cat  home      2.0    1.0        1.0          1.0       1.0
2  cow   ooo      3.0    2.0        2.0          2.0       2.0
3  dog  home      4.0    3.5        4.0          4.0       3.5
4  cat   zoo      NaN    NaN        NaN          NaN       5.0

In [204]:
animal_df["pct-rank"]=animal_df['no-legs'].rank(pct=True)
animal_df

name place  no-legs  rank1  max-rank1  first-rank1  non-rank  pct-rank
0  dog   zoo      4.0    3.5        4.0          3.0       3.5     0.875
1  cat  home      2.0    1.0        1.0          1.0       1.0     0.250
2  cow   ooo      3.0    2.0        2.0          2.0       2.0     0.500
3  dog  home      4.0    3.5        4.0          4.0       3.5     0.875
4  cat   zoo      NaN    NaN        NaN          NaN       5.0       NaN

## Categorise

In [220]:
data_fr=pd.DataFrame({'x':[1,2,3,4,5],'y':[5,6,7,8,9],'z':[2,4,6,8,9]})
data_fr

x  y  z
0  1  5  2
1  2  6  4
2  3  7  6
3  4  8  8
4  5  9  9

In [223]:
data_fr["cc"]=data_fr['y'].astype('category')

In [225]:
data_fr

x  y  z cc
0  1  5  2  5
1  2  6  4  6
2  3  7  6  7
3  4  8  8  8
4  5  9  9  9

In [226]:
data_fr['cc']

0    5
1    6
2    7
3    8
4    9
Name: cc, dtype: category
Categories (5, int64): [5, 6, 7, 8, 9]

In [227]:
data_fr["cc"].cat.categories=['good','bad','avg','execellent','dull']

In [229]:
data_fr

x  y  z          cc
0  1  5  2        good
1  2  6  4         bad
2  3  7  6         avg
3  4  8  8  execellent
4  5  9  9        dull

In [235]:
data_fr["y"]=data_fr['y'].set_categories=['good','bad','avg','execellent','dull']

In [236]:
data_fr

x           y  z          cc
0  1        good  2        good
1  2         bad  4         bad
2  3         avg  6         avg
3  4  execellent  8  execellent
4  5        dull  9        dull

In [237]:
data_fr.groupby('cc')

In [238]:
data_fr

x           y  z          cc
0  1        good  2        good
1  2         bad  4         bad
2  3         avg  6         avg
3  4  execellent  8  execellent
4  5        dull  9        dull

In [240]:
data_fr.groupby('cc').size()

cc
avg           1
bad           1
dull          1
execellent    1
good          1
dtype: int64

In [251]:
df=pd.read_table('sample.txt')

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [252]:
df

a b c
0  1 2 3
1  2 3 4

In [259]:
df=pd.read_table("ex1.csv")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [261]:
df=pd.read_csv("ex1.csv")
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo